# Generated by Django 3.2.8 on 2021-11-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text_description',
        ),
    ]
