# Generated by Django 3.2.8 on 2021-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='_slug',
            field=models.CharField(default='_slug', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
